/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-05 at 17:09:58 UTC 
 * Modify at your own risk.
 */

package com.appspot.observador_electoral.backend.model;

/**
 * Message containing the information of a Clasificacion - name: String holding the name of the
 * Clasificacion - checklist: JSON string of the checklist to fill for this Clasificacion -
 * repeatable: Can only be performed once for a given Casilla
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesCreateClasificacion extends com.google.api.client.json.GenericJson {

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String checklist;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String name;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.Boolean repeatable;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getChecklist() {
        return checklist;
    }

    /**
     * @param checklist checklist or {@code null} for none
     */
    public MessagesCreateClasificacion setChecklist(java.lang.String checklist) {
        this.checklist = checklist;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public MessagesCreateClasificacion setName(java.lang.String name) {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Boolean getRepeatable() {
        return repeatable;
    }

    /**
     * @param repeatable repeatable or {@code null} for none
     */
    public MessagesCreateClasificacion setRepeatable(java.lang.Boolean repeatable) {
        this.repeatable = repeatable;
        return this;
    }

    @Override
    public MessagesCreateClasificacion set(String fieldName, Object value) {
        return (MessagesCreateClasificacion) super.set(fieldName, value);
    }

    @Override
    public MessagesCreateClasificacion clone() {
        return (MessagesCreateClasificacion) super.clone();
    }

}
