/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-03-26 20:30:19 UTC)
 * on 2015-06-05 at 17:09:58 UTC 
 * Modify at your own risk.
 */

package com.appspot.observador_electoral.backend.model;

/**
 * Message containing the information of a Casilla national_id: (String) unique identifier of the
 * Casilla in the national database distrito: (String) unique identifier of the Distrito this
 * casilla belongs to name: (String)
 * <p/>
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the backend. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesCreateCasilla extends com.google.api.client.json.GenericJson {

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String address;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String distrito;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String loc;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String name;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key("national_id")
    private java.lang.String nationalId;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key("picture_url")
    private java.lang.String pictureUrl;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getAddress() {
        return address;
    }

    /**
     * @param address address or {@code null} for none
     */
    public MessagesCreateCasilla setAddress(java.lang.String address) {
        this.address = address;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getDistrito() {
        return distrito;
    }

    /**
     * @param distrito distrito or {@code null} for none
     */
    public MessagesCreateCasilla setDistrito(java.lang.String distrito) {
        this.distrito = distrito;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getLoc() {
        return loc;
    }

    /**
     * @param loc loc or {@code null} for none
     */
    public MessagesCreateCasilla setLoc(java.lang.String loc) {
        this.loc = loc;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * @param name name or {@code null} for none
     */
    public MessagesCreateCasilla setName(java.lang.String name) {
        this.name = name;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getNationalId() {
        return nationalId;
    }

    /**
     * @param nationalId nationalId or {@code null} for none
     */
    public MessagesCreateCasilla setNationalId(java.lang.String nationalId) {
        this.nationalId = nationalId;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public java.lang.String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * @param pictureUrl pictureUrl or {@code null} for none
     */
    public MessagesCreateCasilla setPictureUrl(java.lang.String pictureUrl) {
        this.pictureUrl = pictureUrl;
        return this;
    }

    @Override
    public MessagesCreateCasilla set(String fieldName, Object value) {
        return (MessagesCreateCasilla) super.set(fieldName, value);
    }

    @Override
    public MessagesCreateCasilla clone() {
        return (MessagesCreateCasilla) super.clone();
    }

}
